version: "3.8"

services:

  backend:
    image: "yeshfaandleeb1/greenx-backend:${BUILD_NUMBER}"
    container_name: greenx-backend
    restart: always
    ports:
      - "8089:80"         # Vote Page (Backend)
    environment:
      - NODE_ENV=production

  frontend:
    image: "yeshfaandleeb1/greenx-frontend:${BUILD_NUMBER}"
    container_name: greenx-frontend
    restart: always
    ports:
      - "8088:80"         # Result Page (Frontend)
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge
