version: "3.9"

services:
  backend:
    image: yeshfaandleeb01/greenx-backend:latest
    container_name: greenx-backend
    restart: always
    ports:
      - "8001:8080"

  frontend:
    image: yeshfaandleeb01/greenx-frontend:latest
    container_name: greenx-frontend
    restart: always
    ports:
      - "8002:80"
