sonar.projectKey=docker-task
sonar.projectName=Docker Task Project
sonar.projectVersion=1.0

sonar.sources=GreenX_DCS_Assesment_Tool-main/greenX-assessment-tool-frontend,GreenX_DCS_Assesment_Tool-main/GreenX_DCS_Assesment_Tool_Backend
sonar.sourceEncoding=UTF-8

# Avoid scanning large font files, images, node_modules
sonar.exclusions=**/fonts/**,**/*.ttf,**/*.otf,**/*.woff,**/*.woff2,**/*.png,**/*.jpg,**/*.jpeg,**/*.svg,**/node_modules/**
