sonar.projectKey=docker-task
sonar.projectName=Docker Task Project
sonar.projectVersion=1.0

# Source folders (change if needed)
sonar.sources=GreenX_DCS_Assesment_Tool_Backend,greenX-assessment-tool-frontend

sonar.sourceEncoding=UTF-8
